#
# Dockerfile for key-value storage service
#
FROM golang:1.22 AS build-env

WORKDIR /go/src/github.com/isnastish/kvs/services/kvs

ADD . /go/src/github.com/isnastish/kvs/services/kvs

RUN CGO_ENABLED=0 GOOS=linux go build -a -v -o /go/bin/services/kvs \
    github.com/isnastish/kvs/services/kvs

FROM golang:1.22-alpine3.20 AS run-env

COPY --from=build-env /go/bin/services/kvs /kvs/

EXPOSE 8080/tcp

ENTRYPOINT [ "/kvs/kvs" ]